### ISSUE TITLE
Does it work with content protected by DRM?

### ISSUE THREAD

**Issue by casparom** [webosbrew/hyperion-webos#28]
Hello

A similar tool for android TV-s has on its website this sentence - "**Unfortunately, programs such as YouTube and Netflix use protected content (DRM), Ambient light application has no ability to work with them.**"
Does hyperion-webos library bypass this issue - meaning does it also work with those apps?

Sorry if this is not the correct place to post this question.

Thanks in advance!

**Comment by casparom** [comment]
Im not sure what this means exactly. Does it mean that it does not matter where the image is coming from as long as it is shown on the TV (LG C1 in my case) it is captured? Even if that image is coming from a DRM protected application?

**Comment by Informatic** [comment]
It depends on a TV model. On some TVs DRM protected is blocked, on some it works. From what I heard, works almost everywhere.

We probably want to add "works with protected content" in there: https://github.com/webosbrew/hyperion-webos/issues/16

**Comment by casparom** [comment]
Cool. I'd like to find out if my LG C1 built in Netflix works with this or not before i start rooting my TV etc... :D

**Comment by gotschi** [comment]
does not work on CX 2020

**Comment by tavalin** [comment]
Does not work on 2021 G1 model in Netflix using the libvtcapture backend

**Comment by Informatic** [comment]
Generally seems like anything newer than ~2018-2019 limits capture of DRMed content.

**Comment by TBSniller** [comment]
Due to potential legal issues and also because we don't want to risk any regulations from LG for the OpenLG-Community, we have decieded to stop any further proccess regarding this. 
I've tried to contact some persons from LG and hoped they can create some capture interface for DRM content for us, but sadly they only have answered with some default stuff.. Maybe in some time this project gets bigger and LG sees that there are lots of people buying LG TVs because of native capture, so they do it for us. But until then only this applies:


> On newer TVs there is no official way for capturing DRM-protected content like from Netflix or Amazon. This restriction  doesn't take place for content comming from an HDMI input.
> So currently as a workaround you can play your media using your PC, FireTV-Stick or Chromecast and still enjoy your LEDs.
