### ISSUE TITLE
[3.4.0][libvt] VT_CreateContext Failed

### ISSUE THREAD

**Issue by PaoloVallesi** [webosbrew/hyperion-webos#38]
```
"board_type": "M16_DVB",`
"hardware_id": "HE_DTV_W16N_AFADABAA",`
"product_id": "43UH750V-ZA",`
"core_os_release": "3.4.0-5908",`
"webos_manufacturing_version": "05.60.25",
```

running `./hyperion-webos -b libvt -a 192.168.1.26 -S`
fail to execute with the following log

```
0.001s [INFO main                ] Starting up...
     0.017s [INFO capture_preinit     ] Preinit called. Copying config..
     0.030s [INFO egl_init            ] [EGL] Display, major = 1, minor = 4
     0.035s [INFO egl_init            ] [EGL] Surface size: 360x180
     0.036s [INFO egl_init            ] [EGL] init complete
     0.037s [INFO capture_init        ] [VT] VT_CreateVideoWindow
     0.037s [INFO capture_init        ] [VT] window_id=0
     0.038s [INFO capture_init        ] [VT] VT_AcquireVideoWindowResource
     0.038s [INFO capture_init        ] [VT] resource_id=85
     0.038s [INFO capture_init        ] [VT] VT_CreateContext
KADP_DE_SetDHDRInit : Done.
     0.102s [ ERR capture_init        ] [VT] VT_CreateContext Failed
     0.102s [ ERR capture_main        ] Error! capture_init: -1
     0.103s [ ERR main                ] ERROR: Capture main init failed!
```

I've already tried libdile_vt backend and it stop before that
```
0.000s [INFO main                ] Starting up...
     0.006s [INFO capture_preinit     ] Preinit called. Copying config..
     0.006s [INFO capture_init        ] Init called
     0.006s [INFO capture_start       ] Capture start called.
KADP_DE_SetDHDRInit : Done.
     0.068s [ ERR capture_main        ] Error! capture_start. Code: -2
     0.069s [ ERR main                ] ERROR: Capture main init failed!
```

**Comment by Informatic** [comment]
Someone was attempting that hardware yesterday on Discord, and they managed to get this working by using SCALER dump location instead of DISPLAY. #39 should probably work.

You should be able to download and extract GitHub Actions CI artifact into `/media/developers/apps/usr/palm/services/org.webosbrew.piccap.service` and try again. (you may need to run `pkill -9 -f hyperion-webos` first)

**Comment by PaoloVallesi** [comment]
tried, but i got the same result....
Also, but this should not be related to this git project, piccap cannot resolve root status and save any configuration.
"Start"/"Stop" functions on piccap does not work either.

I was trying to start the backend "piece" first, and then figure out what's going on frontend wise.
if i can run some other command that can help figure it out... i'm a newbie on webos architecture

**Comment by Informatic** [comment]
Regarding start/stop/root status - make sure you are running latest Homebrew Channel version (v0.4.0) - you can check that in Homebrew Channel Settings (or go to Homebrew Channel details page and check if Update button is unclickable)

By "got the same result" you mean getting the same `Error! capture_start. Code: -2` message as before? You should get `DISPLAY dump location failed, attempting SCALER...` warning before that - if not, then you may still be running the old binaries version. Otherwise, we can probably wait for the person that had that issue yesterday to join in with debugging.

**Comment by Informatic** [comment]
FYI just got a confirmation from a person with pretty much the same hardware/software combination that the above PR works fine on `libdile_vt` for them:
```
"board_type": "M16_DVB",
"hardware_id": "HE_DTV_W16N_AFADABAA",
"product_id": "49UH750V-ZA",
"core_os_release": "3.4.0-5908",
"webos_manufacturing_version": "05.60.25"
```

**Comment by willscottuk** [comment]
Hi @PaoloVallesi - if you've installed @Informatic's latest version, could you try running `./hyperion-webos -b libdile_vt -a 192.168.1.26 -S` (it's libdile that should be fixed for the build).

I'm having the same issues with the PicCap interface as you - have been meaning to raise an issue over on that repo.

**Comment by PaoloVallesi** [comment]
> Regarding start/stop/root status - make sure you are running latest Homebrew Channel version (v0.4.0) - you can check that in Homebrew Channel Settings (or go to Homebrew Channel details page and check if Update button is unclickable)
> 
> By "got the same result" you mean getting the same `Error! capture_start. Code: -2` message as before? You should get `DISPLAY dump location failed, attempting SCALER...` warning before that - if not, then you may still be running the old binaries version. Otherwise, we can probably wait for the person that had that issue yesterday to join in with debugging.

Damn, you were right, somehow i didn't "scp" correctly and it kept the old binies, now it works perfectly. Thanks a ton!

**Comment by PaoloVallesi** [comment]
> Hi @PaoloVallesi - if you've installed @Informatic's latest version, could you try running `./hyperion-webos -b libdile_vt -a 192.168.1.26 -S` (it's libdile that should be fixed for the build).
> 
> I'm having the same issues with the PicCap interface as you - have been meaning to raise an issue over on that repo.

please do, i've the 0.4.0 version of homebrew but cannot get piccap to work, i'll +1 the issue.

Closing this one since it's resolved. Thanks!

**Comment by Informatic** [comment]
Regarding start/stop GUI things - we'll need to debug this separately. The issue is that before webOS 4.x native services support was fairly bad. (reminder: by default "services" for installable apps, ie. background processes, are written in NodeJS, but for performance and permissions reasons for libvtcapture, the other backend for newer TVs, we use native C code)

On my webOS 3.8 TV necessary changes for these to work were intergrated in `elevate-service` script in Homebrew Channel v0.4.0 (latest public version) - it's possible some modifications to that script will be necessary on Your TVs, or there's a chance that script is not properly executed on startup. We'll need to check that.

Can you check if this command helps? (after closing PicCap app on the TV, and launching it once again later)
```sh
/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service/elevate-service org.webosbrew.piccap.service
pkill -9 -f hyperion-webos
```

**Comment by PaoloVallesi** [comment]
Tried now, Start/Stop still return the "Denied method call for category {}" like message...
after running those command i got these messages
```
[~] Found legacy webOS <3.x service file: /var/palm/ls2-dev/services/pub/org.webosbrew.piccap.service.service
[-] No changes, no rescan needed
```

but as i said, didnt makes things better...

**Comment by Informatic** [comment]
Sure. That indeed looks like we are missing something to patch still. We'll try to debug this later. :) Thanks for checking!

**Comment by willscottuk** [comment]
I've raised https://github.com/TBSniller/piccap/issues/24 over on PicCap now
